language: node_js

node_js:
  - 0.12

branches:
  only:
    - staging
    - master
    - dev
    - fix-phantom-build-failure

env:
  global:
    # Shippable API token used to trigger deploy
    - secure: ZHB5/RtAQ8vBhJ50mGYp0x5W5cHyPXJ8Y5/MnOas611wh6f8qdG23lEgcwzHsBU+WFgl0SyFXVWIwgOdLKb2mZ5enk+oNVL1SDO9wxnReyS9xvIdinvj/YeFHiv5JF0svNlTebLOeySKgI00EdUGmoM7GcL36VIt0Uu7jfCzjQILcmpnVPNtYtLhpkmNKHUrvCh5xZLtD53GR3mZzOKlC/rLG+g1vaXp0dpAyWyXx2nVAEJgCcAGY6MPMshxLLbZRBRJYxpL20K9cK8smPZbQNWx099kWeZ6t+BAatOTH6cloBkESA6h5aeQaaDBXESosT6j2t2fV0/UreCSxLJbrw==

before_script:
  - npm install --dev
  - npm install -g bower
  - bower install --allow-root -V
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage


script:
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters junit
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters coverage

after_success:
  # Create the version file
  - ./create_version.sh
    
  - sudo docker build -t nrgi/resourceprojects.org:$BRANCH.$COMMIT .
  # Create the `latest` tag and force it in case the tag is already there from a previous build
  - sudo docker tag -f nrgi/resourceprojects.org:$BRANCH.$COMMIT nrgi/resourceprojects.org:$BRANCH

  - sudo docker push nrgi/resourceprojects.org:$BRANCH
  - sudo docker push nrgi/resourceprojects.org:$BRANCH.$COMMIT

  - ./deploy.sh

integrations:
  hub:
    - integrationName: nrgiDockerHub
      type: docker
  notifications:
    - integrationName: email
      type: email
      recipients:
        - nrgi@vitaminsoftware.com
        - kuprina.ks@gmail.com
        - matthew@smartlane.de
      branches:
        only:
          - master
          - staging
      on_success: change
      on_failure: always      
