language: node_js

node_js:
  - 0.12

branches:
  only:
    - staging
    - master
    - dev

before_script:
  - npm install --dev
  - npm install -g bower
  - bower install --allow-root
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage


script:
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters junit
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters coverage

after_success:
  - sudo docker build -t nrgi/resourceprojects.org:$BRANCH.$COMMIT .
  # Create the `latest` tag
  - sudo docker tag -f nrgi/resourceprojects.org:$BRANCH.$COMMIT nrgi/resourceprojects.org:$BRANCH

  - echo $BRANCH
  - sudo docker images
  
  - sudo docker push nrgi/resourceprojects.org:$BRANCH
  - sudo docker push nrgi/resourceprojects.org:$BRANCH.$COMMIT

integrations:
    hub:
      - integrationName: nrgiDockerHub
        type: docker
