language: node_js

node_js:
  - 0.10

branches:
  only:
    - staging
    - master
    - dev

before_script:
  - npm install --dev
  - npm install -g bower
  - bower install
  - bower install --dev
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage


script:
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters junit
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters coverage

after_success:
  - sudo docker build -t nrgi/rp-org-frontend:$BRANCH .
  - sudo docker build -t nrgi/rp-org-frontend:$BRANCH.$BUILD_NUMBER .
  - sudo docker push nrgi/rp-org-frontend:$BRANCH
  - sudo docker push nrgi/rp-org-frontend:$BRANCH.$BUILD_NUMBER

integrations:
    hub:
      - integrationName: nrgiDockerHub
        type: docker