language: node_js

node_js:
  - 0.12

branches:
  only:
    - staging
    - master
    - dev

env:
  global:
    # Shippable API token used to trigger deploy
    - secure: Jk3Dpa4bLBZgoZCnfuRV2odUfCe+MiV417MBRDzrsFdZU8KadjNkmfrS3MBO0Znh4EcNArw79k65fFHJTr4yEUpLT1FVboU/OCBtI0lvzFlB/Pw6o02u2PHImQ5dzHJgrf4A9z8bEIWlEyrQrEzL9r32DWbZ+4blixUUXt7hh74oyRQagt2c6zZAySVZIRv+jsNU27nbCVmFZbkiqStXbJptUAGG1x2nv+oi60XST2AAllodpUiZvZzXafdhqAytZnVqdZqsre/HEEGkgOrsWjt3iIdp2kk13/Uh15m3efVKodFaLapQ49AReOyCSsS5mg5qyjQ1Gvg35hY8474sTA==

before_script:
  - npm install --dev
  - npm install -g bower
  - bower install --allow-root
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage


script:
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters junit
  - node_modules/karma/bin/karma start --browsers=PhantomJS --single-run --reporters coverage

after_success:
  - sudo docker build -t nrgi/resourceprojects.org:$BRANCH.$COMMIT .
  # Create the `latest` tag and force it in case the tag is already there from a previous build
  - sudo docker tag -f nrgi/resourceprojects.org:$BRANCH.$COMMIT nrgi/resourceprojects.org:$BRANCH

  - sudo docker push nrgi/resourceprojects.org:$BRANCH
  - sudo docker push nrgi/resourceprojects.org:$BRANCH.$COMMIT

  - ./deploy.sh

integrations:
    hub:
      - integrationName: nrgiDockerHub
        type: docker
